# Generated by Django 3.0.6 on 2020-09-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=models.TextField(default='Hello'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='Hello'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.ImageField(default='images/item-3.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_img',
            field=models.ImageField(default='images/item-3.png', upload_to='images/'),
        ),
    ]
